Added AutoLayout helper
allaboutapps/Toolbox pull request #10
Opened 2020-11-06 13:07 UTC by oliverkrakora

#3

2020-11-06 13:17 UTC, swieland requested changes

2020-11-06 13:17 UTC, swieland commented on Sources/Toolbox/Extensions/UIView+AutoLayout.swift
> +            bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: offset.bottom)
This will cause a negative offset.
replace with:
`view.bottomAnchor.constraint(equalTo: bottomAnchor, constant: offset.bottom`

2020-11-06 13:17 UTC, swieland commented on Sources/Toolbox/Extensions/UIView+AutoLayout.swift
> +        self.translatesAutoresizingMaskIntoConstraints = false
remove self

2020-11-11 08:10 UTC, wieweb approved these changes

2020-11-11 08:11 UTC, merged